services:
  hhvm:
    container_name: theodore-sql-queryf-codegen-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48565:10641
